<p class="font-weight-bold">Fragen zum Datenschutz und Wahrnehmung Ihrer Rechte</p>
<p>Für Fragen zum Datenschutz oder für die Ausübung der Ihnen zustehenden datenschutzrechtlichen Ansprüche wenden Sie sich bitte an die oben genannten Kontaktdaten.</p>
<p class="font-weight-bold">Technischer Betrieb unserer Webseite</p>
<p>Wenn Sie mit Ihrem Browser unsere Webseite aufrufen, übermittelt dieser an uns verschiedene personenbezogene Daten. Von diesen verarbeiten wir die sog. IP-Adresse, damit der von Ihnen verwendete Browser Inhalte unsere Webseite abrufen und sie damit nutzen kann.
    Rechtsgrundlage für diese Verarbeitung der IP-Adresse ist Art. 6 Abs. 1 lit. f) DSGVO, da mit dem Besuch unserer Webseite es auch in Ihrem Interesse liegt, dass wir deren Nutzung technisch ermöglichen. Sofern der Besuch unserer Webseite dem Abschluss eines Vertrages oder der Vorbereitung dessen dient, ist Rechtsgrundlage der Verarbeitung Art. 6 Abs. 1 lit. b) DSGVO. Diese Daten werden nicht über die technisch erforderliche Dauer hinaus gespeichert.
</p>
<p class="font-weight-bold">Nutzungsstatistiken für unsere Webseite</p>
<p>Wenn Sie mit Ihrem Browser unsere Webseite aufrufen, übermittelt dieser automatisch an uns verschiedene personenbezogene Daten. Von diesen Daten nutzen wir die nachfolgend Genannten, um ohne Bezug zu einer bestimmten Person statistische Auswertungen zu erstellen, wie und unter welchen technischen Voraussetzungen unsere Webseite genutzt wird, um Fehler zu erkennen und Verbesserungen (z.B. in der Benutzerführung) vornehmen zu können:</p>
<ul>
    <li>Datum und Uhrzeit des Zugriffs</li>
    <li>Name und URL der abgerufenen Datei</li>
    <li>Website, von der aus der Zugriff erfolgt (Referrer-URL)</li>
    <li>Verwendeter Browser, Betriebssystem des Endgerätes</li>
</ul>
<p>Die Daten werden nicht im Zusammenhang mit anderen Daten verarbeitet, die es uns ermöglichen würden, einen Personenbezug herzustellen. Es werden daher keine personenbezogenen Nutzerprofile erstellt. Rechtsgrundlage für die Verwendung der Daten für die Erstellung der Statistiken ist Art. 6 Abs. 1 lit. f) DSGVO. Unser berechtigtes Interesse für eine entsprechende Verarbeitung ist, dass es uns diese Statistiken ermöglichen, Fehlfunktionen unserer Webseite zu erkennen und sie zu optimieren, damit die Nutzung der Webseite möglichst den Interessen den Nutzer entspricht und damit erfolgreich von uns eingesetzt werden kann.</p>
<p class="font-weight-bold">Erkennung und Abwehr von Angriffen gegen unsere Webseite</p>
<p>Wir verarbeiten Ihre IP-Adressen zusammen mit Datum und Uhrzeit des Zugriffes beschränkt auf diesen Zweck für die Erkennung und Abwehr von Angriffen gegen die Systeme, die für den Betrieb unserer Webseite eingesetzt werden. Durch solche Angriffe könnte die bestimmungsgemäße Funktionsfähigkeit der Systeme, die Nutzung unserer Webseite bzw. deren Funktionsfähigkeit sowie die Sicherheit der Besucher unserer Webseite beeinträchtigt werden. Wir verfolgen hiermit das berechtigte Interesse, die Verarbeitungssicherheit nach Art. 32 DSGVO sicherzustellen, Angriffe zu erkennen sowie abzuwehren, um damit uns und die Besucher unserer Webseite vor Schäden zu schützen. Empfänger dieser Daten können Strafverfolgungsbehörden sowie (technische) Dienstleister sein, die uns bei der Erkennung oder Abwehr der Angriffe unterstützen. Rechtsgrundlage der Verarbeitung ist Art. 6 Abs. 1 lit. f) DSGVO. Die IP-Adressen werden nach 3 Monate gelöscht, sofern für die vorstehenden Zwecke nicht im Einzelfall eine weitere Speicherung erforderlich ist. In diesem Fall löschen wir die Daten mit Fortfall des Zwecks. </p>
<p class="font-weight-bold">Anlegen eines Kundenkontos</p>
<p>Wenn Sie ein Kundenkonto auf unserer Webseite anlegen, verarbeiten wir die von Ihnen angegebenen Daten, um das Kundenkonto einzurichten, zu verwalten und um Ihnen die Inanspruchnahme der Leistungen zu ermöglichen, die wir im Zusammenhang mit dem Kundenkonto anbieten. In dem Kundenkonto werden neben den Daten, die Sie bei der Einrichtung angegeben, ggf. weitere Daten verarbeitet, die im Zusammenhang mit der Nutzung des Kontos anfallen, wie z.B. eine Bestellhistorie. Rechtsgrundlage für die entsprechende Verarbeitung Ihrer Daten ist Art. 6 Abs. 1 lit. b) DSGVO.
    An die von Ihnen bei Anmeldung angegebene E-Mail-Adresse senden wir eine E-Mail mit der Bitte um Bestätigung der Anmeldung. Hiermit wollen wir zu Ihrem und zu unserem Schutz verhindern, dass Dritte unter Missbrauch Ihrer E-Mail-Adresse ein Kundenkonto eröffnen. Rechtsgrundlage hierfür ist Art. 6 Abs. 1 lit. f) DSGVO.
    Diese mit dem Kundenkonto zusammenhängenden Daten werden bis zur Löschung des Kundenkontos gespeichert. Sofern wir gesetzlich zu einer längeren Speicherung verpflichtet sind (z.B. zur Erfüllung von Buchhaltungspflichten oder gesetzlich vorgeschriebenen Nachweisen) oder wir gesetzlich zu einer längeren Speicherung berechtigt sind (z.B. wegen eines laufenden Rechtsstreits gegen den Inhaber eines Kundenkontos), erfolgt die Löschung nach Ablauf der Speicherverpflichtung bzw. der Berechtigung.
</p>
<p class="font-weight-bold">Email-Newsletter</p>
<p>Mit Ihrer Anmeldung zu unserem Email-Newsletter verarbeiten wir die von Ihnen hierbei angegebenen Daten. Wir verwenden diese für die Erstellung und den Versand unseres Newsletters. Rechtsgrundlage der Verarbeitung ist aufgrund Ihrer Einwilligung Art. 6 Abs. 1 lit. a) DSGVO. Sie können Ihre Einwilligung jederzeit mit Wirkung für die Zukunft widerrufen. Durch den Widerruf der Einwilligung wird die Rechtmäßigkeit der aufgrund der Einwilligung bis zum Widerruf erfolgten Verarbeitung nicht berührt.
    Für die Bestätigung Ihrer Anmeldung zum Newsletter müssen Sie auf den Bestätigungslink in der Verifizierungsemail klicken, die wir Ihnen nach Ihrer Anmeldung übersenden. Mit einem Klick auf den angegebenen Link in der Verifizierungsnachricht verarbeiten wir Datum und Uhrzeit des Klicks, den Inhalt der an Sie gesandten Nachricht sowie die verwendete Email-Adresse. Dies erfolgt, um den Nachweis erbringen zu können, dass Sie sich zu dem Newsletter angemeldet und Ihre Einwilligung bestätigt haben. Rechtsgrundlage dieser Verarbeitung ist Art. 6 Abs. 1 lit. c) DSGVO, da wir gesetzlich verpflichtet sind, Ihre Einwilligung nachweisen zu können.
    Wir löschen Ihre mit dem Newsletter-Abo im Zusammenhang stehenden personenbezogenen Daten mit Ihrer Abmeldung. Daten, die wir als Nachweis benötigen, dass Sie sich zu dem Newsletter angemeldet haben, löschen wir nach Ablauf der Verjährungsfrist für entsprechende Nachweispflichten.
</p>
<p class="font-weight-bold">Ihre Rechte</p>
<p>Ihnen stehen im Zusammenhang mit Ihren personenbezogenen Daten aus der DSGVO insbesondere die nachfolgend genannten Rechte zu. Wegen der Details verweisen wir auf die gesetzlichen Regelungen (insbesondere Art. 15 ff. DSGVO).</p>
<p class="font-weight-bold">Recht auf Auskunft</p>
<p>Nach Art. 15 DSGVO haben Sie das Recht, von uns eine Bestätigung darüber zu verlangen, ob durch uns Sie betreffende personenbezogene Daten verarbeitet werden. Wenn dies der Fall der Fall sein sollte, haben Sie ein Recht auf Auskunft über diese personenbezogenen Daten und auf weitergehende Informationen, die in Art. 15 DSGVO genannt sind.</p>
<p class="font-weight-bold">Recht auf Berichtigung</p>
<p>Nach Art. 16 DSGVO haben Sie das Recht, von uns unverzüglich die Berichtigung unrichtiger personenbezogener Daten zu verlangen, die Sie betreffen. Unter Berücksichtigung der Zwecke der Verarbeitung haben Sie ferner das Recht, die Vervollständigung unvollständiger personenbezogener Daten – auch mittels einer ergänzenden Erklärung – zu verlangen.</p>
<p class="font-weight-bold">Recht auf Löschung ("Recht auf Vergessenwerden")</p>
<p>Sie haben in den Grenzen des Art. 17 DSGVO das Recht von uns zu verlangen, dass Sie betreffende personenbezogene Daten unverzüglich gelöscht werden. Wir sind verpflichtet, personenbezogene Daten unverzüglich zu löschen, sofern die entsprechenden Voraussetzungen des Art. 17 DSGVO vorliegen. Wegen der Einzelheiten verweisen wir auf Art. 17 DSGVO. </p>
<p class="font-weight-bold">Recht auf Einschränkung der Verarbeitung </p>
<p>Nach Maßgabe des Art. 18 DSGVO haben Sie unter bestimmten Voraussetzungen das Recht, von uns die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen. Wegen der Einzelheiten verweisen wir auf Art. 18 DSGVO. </p>
<p class="font-weight-bold">Recht auf Datenübertragbarkeit</p>
<p>Unter den Voraussetzungen des Art. 20 DSGVO haben Sie das Recht, die Sie betreffenden personenbezogenen Daten, die Sie uns bereitgestellt haben, in einem strukturierten, gängigen und maschinenlesbaren Format zu erhalten. Nach Art. 20 DSGVO haben Sie weiter das Recht, diese Daten einem anderen Verantwortlichen ohne Behinderung durch uns zu übermitteln, sofern die Verarbeitung auf einer Einwilligung gemäß Artikel 6 Abs. 1 lit. a) DSGVO oder Artikel 9 Abs. 2 lit. a) DSGVO oder auf einem Vertrag gemäß Artikel 6 Abs. 1 lit. b) DSGVO beruht und die Verarbeitung mithilfe automatisierter Verfahren erfolgt.</p>
<p class="font-weight-bold">Bestehen eines Beschwerderechts bei der Aufsichtsbehörde</p>
<p>Sie haben nach Art. 77 DSGVO unbeschadet eines anderweitigen verwaltungsrechtlichen oder gerichtlichen Rechtsbehelfs das Recht, sich bei der Aufsichtsbehörde zu beschweren. Dieses Recht besteht insbesondere in dem Mitgliedstaat Ihres Aufenthaltsorts, Ihres Arbeitsplatzes oder des Orts des mutmaßlichen Verstoßes, wenn Sie der Ansicht sind, dass die Verarbeitung der Sie betreffenden personenbezogenen Daten gegen die DSGVO verstößt.</p>
<p class="font-weight-bold">Widerspruchsrecht </p>
<p>Nach Art. 21 DSGVO haben Sie das Recht gegen die Verarbeitung Sie betreffender personenbezogener Daten, die auf Grundlage von Artikel 6 Absatz 1 lit. e oder lit. f DSGVO erfolgt, Widerspruch einzulegen; dies gilt auch für ein auf diese Bestimmungen gestütztes Profiling. <br> Sofern wir Ihre personenbezogenen Daten verarbeiten, um Direktwerbung zu betreiben, haben Sie jederzeit das Recht, gegen die Verarbeitung sie betreffender personenbezogener Daten zum Zwecke derartiger Werbung Widerspruch einzulegen; dies gilt auch für das Profiling, soweit es mit solcher Direktwerbung in Verbindung steht.
</p>

